apiVersion: v1
kind: Service
metadata:
  name: [service-name]
  labels:
    name: [service-name]
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: [service-name]
